### PR TITLE
change route() to multiprocessing style

### PR DESCRIPTION
**Pull request by michaeleekk**
Added `multiprocessing` dependency for running `distributeTask()` in a subprocess.

### CODE REVIEW

**Comment by z5ouyang** [comment]
Hi @michaeleekk, Thank you very much for setting the PR. I don't think this works for the following two reasons (please correct me if I am wrong):
1. This seems not the multiprocessing, each job quested from UI will send to server independently. Thus, at any time there is only one job in "Process". You can test this by send a UI job which take a bit longer, and while server is working on it, you send several more jobs from UI. You can then observe the server still working one job at a time.
2. Even this works for multiprocessing, I don't think this solves the "memory leak" problem, actually making it worse. Because now you have two or more parallel processes to do DEG on a large dataset (seems like diffxy making internal copy of data), then you will be out of memory. You can test this, by open two or more browser instances, and submit DEG on each one of them, (you can use this to observe the multi-process as well), if multi-process work, memory usage will be double (multiple) times.

let me know what's your thought.
Thanks again for the PR.
O'Young

**Comment by michaeleekk** [comment]
@z5ouyang Thanks for the comments. Let me clear your doubts :)

1. The code is from `multiprocessing` Python module so I named the PR as is. The code could potentially work for processing multiple requests at the same time but I decided not to make a big changes on the repo. The main point that is prohibiting it is your original code of having the `jobLock` in `route()`. I believe you wrote that for a reason, for example other code would break if they are used at the same time. So I decided to keep the PR small by keeping the `jobLock`.
2. I guess we might have a misunderstanding here. Memory leak doesn't mean you can process a lot of processes at the same time with insufficient memory. Memory leak means that when one part of code is completed, the memory usage will go back to the point when it's entering that part of code, i.e. there are no remaining objects, etc. in the memory after that part of code is finished. So if you would like to process a lot of huge datasets at the same time, you still need to provide enough memory to do so, but the point of this PR is memory leak.

I hope I make myself clear on the code  :)

**Comment by z5ouyang** [comment]
Hi @michaeleekk, thanks for explaining. I might misunderstand you at beginning. If I am understanding this correctly, the PR is not fix the memory leak issue, but let the "multiprocessing" handle/do memory cleaning (garbage collection)? If it is, I will try to find the real cause and attempt to fix the issue. Will keep you posted. If you have additional information (additional test), please let me know. Thanks again for this!

**Comment by z5ouyang** [comment]
This is not a memory leak after some testing. It is related to how python's "garbage collection". The large data generated within a function is not freed at then end of function immediately. Just added "gc.collect()" in 32e72188dcaa4ac026e58b28fba2dd2ec313a36e  after task is done to force python to do "garbage collection" solved the memory increasing issue.
Thanks @michaeleekk for reporting this issue!

**Pull request closed without merging**
